version: '3.7'

x-build_context:
  &x-build_context
  context: .

x-django:
  &x-django
  environment:
    ALLOWED_HOSTS: >-
      localhost
    DATABASE_URL: postgresql://postgres@db:5432/fortnite_server
    WAIT_HOSTS: db:5432
  volumes:
    - .:/code
    - venv:/venv
    - ./ssh:/home/app/.ssh
  stdin_open: true
  tty: true

services:
  db:
    image: mysql:5.6.36
    container_name: db
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 13306:3306

  backend:
    container_name: backend
    <<: *x-django
    build:
      <<: *x-build_context
      dockerfile: Dockerfile-backend
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  mysql_data:
  venv:
