version: '3.7'

services:
  db:
    image: postgres
  backend:
    build: .
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
