# Generated by Django 3.0 on 2019-12-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Group name')),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='variants',
            field=models.CharField(choices=[(0, 'COMMON'), (1, 'UNCOMMON'), (2, 'RARE'), (3, 'EPIC'), (4, 'LEGENDARY')], default=1, max_length=10, verbose_name='Variant'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Item name')),
                ('variants', models.CharField(choices=[(0, 'COMMON'), (1, 'UNCOMMON'), (2, 'RARE'), (3, 'EPIC'), (4, 'LEGENDARY')], default=1, max_length=10, verbose_name='Variant')),
                ('image', models.ImageField(upload_to='', verbose_name='Item image')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Is removed ?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='app.ItemGroup', verbose_name='Item group')),
            ],
        ),
    ]
