# Generated by Django 3.0 on 2019-12-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191208_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationItems',
            new_name='LocationItem',
        ),
    ]
