# Generated by Django 3.0 on 2019-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191208_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True, verbose_name='Season #')),
                ('version', models.FloatField(verbose_name='Ingame version')),
            ],
        ),
    ]
