# Generated by Django 3.0 on 2019-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='weapondetail',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
