# Generated by Django 3.0 on 2019-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191209_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(help_text='Precise image name with extension.', max_length=100, verbose_name='Item image name'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.CharField(help_text='Precise image name with extension.', max_length=100, verbose_name='Weapon image name'),
        ),
    ]
