# Generated by Django 3.0 on 2019-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191209_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapondetail',
            old_name='environement_damages',
            new_name='environment_damages',
        ),
    ]
