# Generated by Django 3.0 on 2019-12-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191209_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('data', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='Information limited ?'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_incomplete',
            field=models.BooleanField(default=False, verbose_name='Information limited ?'),
        ),
    ]
